server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
      - "optional:configserver:http://localhost:8071/"

build:
  version: "3.0.0"

cards:
  message: "Welcome to Banks Account related local APIs"
  contactDetails:
    name: "John Doe - Software Engineer"
    email: "john@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1345

management:
  endpoints:
    web:
      exposure:
        include: "*"