spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0.0"

accounts:
  message: "Welcome to Banks Account related prod APIs"
  contactDetails:
    name: "Reine - Product Manager"
    email: "reine@gmail.com"
  onCallSupport:
    - (453) 555-1234
    - (236) 555-1345