build:
  version: "3.0.0"

cards:
  message: "Welcome to Banks Account related local APIs"
  contactDetails:
    name: "John Doe - Software Engineer"
    email: "john@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1345