services:
  configserver:
    image: "banks/configserver"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "banks/accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
      SPRING_PROFILES_ACTIVE: default
#      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
    depends_on:
      - accountsdb
      - configserver
    networks:
      - banks

  loans:
    image: "banks/loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      - configserver
      - loansdb
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3307/loansdb"
    networks:
      - banks

  cards:
    image: "banks/cards"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      - configserver
      - cardsdb
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3308/cardsdb"
    networks:
      - banks

  accountsdb:
    image: mysql
    container_name: accountsdb
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: network-deploy-service

  cardsdb:
    image: mysql
    container_name: cardsdb
    ports:
      - 3308:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: network-deploy-service

  loansdb:
    image: mysql
    container_name: loansdb
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: network-deploy-service

networks:
  banks:
    driver: "bridge"