services:
  configserver:
    image: "banks/configserver"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "banks/accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "banks/loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      - configserver
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "loans"
    networks:
      - banks

  cards:
    image: "banks/cards"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      - configserver
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "cards"
    networks:
      - banks

networks:
  banks:
    driver: "bridge"